# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14u_lwmNES29A8Fog_odIwGkYkjoTHNdR
"""

import torch
import torchvision
from torchvision import transforms, datasets
from torch.utils.data import DataLoader

import matplotlib.pyplot as plt
import numpy as np


from enum import Enum

import torch.nn as nn
import torch.optim as optim
from torchvision import models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

transform = transforms.Compose([
    transforms.Resize((224, 224)), # Resizes the image to be a standard size
    transforms.ToTensor(), # Converts the image to tensor
    transforms.Normalize(mean=[0.485, 0.456, 0.406], # Normalizes the image
                         std=[0.229, 0.224, 0.225])
])

from google.colab import drive
drive.mount('/content/drive')

!ls /content/

train_dataset = datasets.ImageFolder(root='/content/drive/MyDrive/colab/fracture_dislocation', transform=transform)
val_dataset = datasets.ImageFolder(root='/content/drive/MyDrive/colab/fracture_dislocation', transform=transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=4)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=4)

class_names = train_dataset.classes
num_classes = class_names.__len__()

label_enum = Enum('ClassEnum', {name: idx for idx, name in enumerate(class_names)})

print(class_names)
print(num_classes)

# Defining our own CNN

class BoneFractureModel(nn.Module):
    def __init__(self, num_classes, input_size=(3, 224, 224)):
        super(BoneFractureModel, self).__init__()

        self.conv_layers = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2,2),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2,2),

            nn.Conv2d(64, 128, 3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2,2),
        )

        # Automatically compute flatten size based on input image
        with torch.no_grad():
            dummy_input = torch.zeros(1, *input_size)  # matches your actual image size
            dummy_output = self.conv_layers(dummy_input)
            flatten_size = dummy_output.view(1, -1).size(1)

        self.fc_layers = nn.Sequential(
            nn.Linear(flatten_size, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        x = self.conv_layers(x)
        x = x.view(x.size(0), -1)
        x = self.fc_layers(x)
        return x

# training and validation function

def train_and_validate(model, train_loader, val_loader, num_epochs=10, learning_rate=0.001, device=None):
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    # Loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    for epoch in range(num_epochs):
        # --- Training ---
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:
            images = images.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        train_loss = running_loss / total
        train_acc = correct / total

        # --- Validation ---
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0
        with torch.no_grad():
            for images, labels in val_loader:
                images = images.to(device)
                labels = labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item() * images.size(0)
                _, predicted = torch.max(outputs, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        val_loss /= val_total
        val_acc = val_correct / val_total

        print(f"Epoch {epoch+1}/{num_epochs} — "
              f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f} — "
              f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.4f}")

    print("Training complete!")

# Initialize our model as our used defined BoneFractureModel
model = BoneFractureModel(num_classes)

# Optional: print our model
print(model)

# Move Model to the GPU if available
model.to(device)

# Train the Model
train_and_validate(model, train_loader, val_loader, num_epochs=5, learning_rate=0.001)